import { Artifact } from '../../registry/types';

export const ARTIFACTS: readonly Artifact[] = [
    {
        id: 'ARTEFAKT_08_SECURITY_POLICY',
        displayNameSL: 'Security Policy',
        descriptionSL: 'Varnostna politika',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['security', 'policy', 'yaml'],
        artifactKind: 'DOCUMENT',
        format: 'yaml',
        mimeType: 'application/yaml',
        producedByStepId: 'KORAK_08_POLICY_DESIGN',
        consumedByStepIds: ['KORAK_08_COMPLIANCE_CHECK'],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_VULNERABILITY_REPORT',
        displayNameSL: 'Vulnerability Report',
        descriptionSL: 'Porocilo o ranljivostih',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['vulnerability', 'scan', 'report'],
        artifactKind: 'REPORT',
        format: 'json',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_VULN_SCAN',
        consumedByStepIds: ['KORAK_08_REMEDIATION'],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_SAST_REPORT',
        displayNameSL: 'SAST Report',
        descriptionSL: 'Porocilo staticne analize varnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sast', 'static', 'analysis'],
        artifactKind: 'REPORT',
        format: 'sarif',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_SAST',
        consumedByStepIds: [],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_DAST_REPORT',
        displayNameSL: 'DAST Report',
        descriptionSL: 'Porocilo dinamicne analize varnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['dast', 'dynamic', 'analysis'],
        artifactKind: 'REPORT',
        format: 'json',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_DAST',
        consumedByStepIds: [],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_SBOM',
        displayNameSL: 'Security SBOM',
        descriptionSL: 'Varnostni SBOM',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sbom', 'cyclonedx', 'dependencies'],
        artifactKind: 'SBOM',
        format: 'json',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_SBOM_GEN',
        consumedByStepIds: ['KORAK_08_VULN_SCAN'],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_PENTEST_REPORT',
        displayNameSL: 'Penetration Test Report',
        descriptionSL: 'Porocilo o penetracijskem testu',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['pentest', 'penetration', 'test'],
        artifactKind: 'REPORT',
        format: 'pdf',
        mimeType: 'application/pdf',
        producedByStepId: 'KORAK_08_PENTEST',
        consumedByStepIds: [],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_SECRETS_SCAN',
        displayNameSL: 'Secrets Scan Report',
        descriptionSL: 'Porocilo o skeniranju skrivnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['secrets', 'scan', 'gitleaks'],
        artifactKind: 'REPORT',
        format: 'json',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_SECRETS_SCAN',
        consumedByStepIds: [],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    },
    {
        id: 'ARTEFAKT_08_COMPLIANCE_REPORT',
        displayNameSL: 'Compliance Report',
        descriptionSL: 'Porocilo o skladnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/artifacts',
        domainId: 'DOMENA_08',
        type: 'ARTIFACT',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['compliance', 'audit', 'report'],
        artifactKind: 'REPORT',
        format: 'json',
        mimeType: 'application/json',
        producedByStepId: 'KORAK_08_COMPLIANCE_CHECK',
        consumedByStepIds: [],
        hashAlgorithm: 'SHA-256',
        contentHash: '',
        sizeBytes: null
    }
];
