import { EvidenceItem } from '../../registry/types';

export const EVIDENCE_ITEMS: readonly EvidenceItem[] = [
    {
        id: 'EVI_08_SAST_REPORT',
        displayNameSL: 'SAST Report Evidence',
        descriptionSL: 'Dokaz SAST porocila',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/evidence',
        domainId: 'DOMENA_08',
        type: 'EVIDENCE_ITEM',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sast', 'evidence'],
        evidenceKind: 'SCAN_REPORT',
        sourceActivityId: 'VERIFIKACIJA_08_SAST_REVIEW',
        referencedArtifactIds: ['ARTEFAKT_08_SAST_REPORT'],
        referencedStepIds: ['KORAK_08_SAST'],
        format: 'sarif',
        contentHash: '',
        generatedAt: '',
        expiresAt: null,
        signedBy: null
    },
    {
        id: 'EVI_08_VULN_REPORT',
        displayNameSL: 'Vulnerability Report Evidence',
        descriptionSL: 'Dokaz porocila o ranljivostih',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/evidence',
        domainId: 'DOMENA_08',
        type: 'EVIDENCE_ITEM',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['vulnerability', 'evidence'],
        evidenceKind: 'SCAN_REPORT',
        sourceActivityId: 'VERIFIKACIJA_08_VULN_ASSESSMENT',
        referencedArtifactIds: ['ARTEFAKT_08_VULNERABILITY_REPORT'],
        referencedStepIds: ['KORAK_08_VULN_SCAN'],
        format: 'json',
        contentHash: '',
        generatedAt: '',
        expiresAt: null,
        signedBy: null
    },
    {
        id: 'EVI_08_SECRETS_AUDIT',
        displayNameSL: 'Secrets Audit Evidence',
        descriptionSL: 'Dokaz revizije skrivnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/evidence',
        domainId: 'DOMENA_08',
        type: 'EVIDENCE_ITEM',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['secrets', 'audit'],
        evidenceKind: 'AUDIT_LOG',
        sourceActivityId: 'VERIFIKACIJA_08_SECRETS_AUDIT',
        referencedArtifactIds: ['ARTEFAKT_08_SECRETS_SCAN'],
        referencedStepIds: ['KORAK_08_SECRETS_SCAN'],
        format: 'json',
        contentHash: '',
        generatedAt: '',
        expiresAt: null,
        signedBy: null
    },
    {
        id: 'EVI_08_COMPLIANCE_REPORT',
        displayNameSL: 'Compliance Report Evidence',
        descriptionSL: 'Dokaz porocila o skladnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/evidence',
        domainId: 'DOMENA_08',
        type: 'EVIDENCE_ITEM',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['compliance', 'evidence'],
        evidenceKind: 'ANALYSIS_REPORT',
        sourceActivityId: 'VERIFIKACIJA_08_COMPLIANCE_AUDIT',
        referencedArtifactIds: ['ARTEFAKT_08_COMPLIANCE_REPORT'],
        referencedStepIds: ['KORAK_08_COMPLIANCE_CHECK'],
        format: 'json',
        contentHash: '',
        generatedAt: '',
        expiresAt: null,
        signedBy: null
    },
    {
        id: 'EVI_08_PENTEST_REPORT',
        displayNameSL: 'Pentest Report Evidence',
        descriptionSL: 'Dokaz penetracijskega testa',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/evidence',
        domainId: 'DOMENA_08',
        type: 'EVIDENCE_ITEM',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['pentest', 'evidence'],
        evidenceKind: 'SCAN_REPORT',
        sourceActivityId: 'VERIFIKACIJA_08_PENTEST_REVIEW',
        referencedArtifactIds: ['ARTEFAKT_08_PENTEST_REPORT'],
        referencedStepIds: ['KORAK_08_PENTEST'],
        format: 'pdf',
        contentHash: '',
        generatedAt: '',
        expiresAt: null,
        signedBy: null
    }
];
