import { DomainPack } from '../../registry/types';
import { DOMAIN } from './domain';
import { CATEGORY as CAT_08_CRYPTO } from './categories/KATEGORIJA_08_CRYPTO';
import { CATEGORY as CAT_08_AUTH } from './categories/KATEGORIJA_08_AUTH';
import { SUBCATEGORY as SUBCAT_08_SYMMETRIC } from './subcategories/PODKATEGORIJA_08_SYMMETRIC';
import { SUBCATEGORY as SUBCAT_08_ASYMMETRIC } from './subcategories/PODKATEGORIJA_08_ASYMMETRIC';
import { SUBCATEGORY as SUBCAT_08_MFA } from './subcategories/PODKATEGORIJA_08_MFA';
import { MODULE as MOD_08_AES } from './modules/MODUL_08_AES';
import { MODULE as MOD_08_RSA } from './modules/MODUL_08_RSA';
import { MODULE as MOD_08_TOTP } from './modules/MODUL_08_TOTP';
import { MODULE as MOD_08_HASHING } from './modules/MODUL_08_HASHING';
import { MODULE as MOD_08_KEY_DERIVATION } from './modules/MODUL_08_KEY_DERIVATION';
import { MODULE as MOD_08_SECURE_RANDOM } from './modules/MODUL_08_SECURE_RANDOM';
import { MODULE as MOD_08_VULNERABILITY } from './modules/MODUL_08_VULNERABILITY';
import { SUBMODULE as SUBMOD_08_AES_CORE } from './submodules/PODMODUL_08_AES_CORE';
import { SUBMODULE as SUBMOD_08_RSA_CORE } from './submodules/PODMODUL_08_RSA_CORE';
import { SUBMODULE as SUBMOD_08_TOTP_CORE } from './submodules/PODMODUL_08_TOTP_CORE';
import { SUBMODULE as SUBMOD_08_HASHING_CORE } from './submodules/PODMODUL_08_HASHING_CORE';
import { SUBMODULE as SUBMOD_08_KEY_DERIVATION_CORE } from './submodules/PODMODUL_08_KEY_DERIVATION_CORE';
import { SUBMODULE as SUBMOD_08_SECURE_RANDOM_CORE } from './submodules/PODMODUL_08_SECURE_RANDOM_CORE';
import { SUBMODULE as SUBMOD_08_VULNERABILITY_CORE } from './submodules/PODMODUL_08_VULNERABILITY_CORE';
import { FUNCTIONS as SUBMOD_08_AES_CORE_FNS } from './functions/PODMODUL_08_AES_CORE_functions';
import { FUNCTIONS as SUBMOD_08_RSA_CORE_FNS } from './functions/PODMODUL_08_RSA_CORE_functions';
import { FUNCTIONS as SUBMOD_08_TOTP_CORE_FNS } from './functions/PODMODUL_08_TOTP_CORE_functions';
import { FUNCTIONS as SUBMOD_08_HASHING_CORE_FNS } from './functions/PODMODUL_08_HASHING_CORE_functions';
import { FUNCTIONS as SUBMOD_08_KEY_DERIVATION_CORE_FNS } from './functions/PODMODUL_08_KEY_DERIVATION_CORE_functions';
import { FUNCTIONS as SUBMOD_08_SECURE_RANDOM_CORE_FNS } from './functions/PODMODUL_08_SECURE_RANDOM_CORE_functions';
import { FUNCTIONS as SUBMOD_08_VULNERABILITY_CORE_FNS } from './functions/PODMODUL_08_VULNERABILITY_CORE_functions';

import { MODULE as MOD_08_AUTH } from './modules/MODUL_08_AUTH';
import { SUBMODULE as SUBMOD_08_AUTH_JWT } from './submodules/PODMODUL_08_AUTH_JWT';
import { FUNCTIONS as PODMODUL_08_AUTH_JWT_FNS } from './functions/PODMODUL_08_AUTH_JWT_functions';
import { SUBMODULE as SUBMOD_08_AUTH_OAUTH } from './submodules/PODMODUL_08_AUTH_OAUTH';
import { FUNCTIONS as PODMODUL_08_AUTH_OAUTH_FNS } from './functions/PODMODUL_08_AUTH_OAUTH_functions';
import { SUBMODULE as SUBMOD_08_AUTH_SESSION } from './submodules/PODMODUL_08_AUTH_SESSION';
import { FUNCTIONS as PODMODUL_08_AUTH_SESSION_FNS } from './functions/PODMODUL_08_AUTH_SESSION_functions';
import { MODULE as MOD_08_RBAC } from './modules/MODUL_08_RBAC';
import { SUBMODULE as SUBMOD_08_RBAC_ROLES } from './submodules/PODMODUL_08_RBAC_ROLES';
import { FUNCTIONS as PODMODUL_08_RBAC_ROLES_FNS } from './functions/PODMODUL_08_RBAC_ROLES_functions';
import { SUBMODULE as SUBMOD_08_RBAC_PERMISSIONS } from './submodules/PODMODUL_08_RBAC_PERMISSIONS';
import { FUNCTIONS as PODMODUL_08_RBAC_PERMISSIONS_FNS } from './functions/PODMODUL_08_RBAC_PERMISSIONS_functions';
import { SUBMODULE as SUBMOD_08_RBAC_POLICIES } from './submodules/PODMODUL_08_RBAC_POLICIES';
import { FUNCTIONS as PODMODUL_08_RBAC_POLICIES_FNS } from './functions/PODMODUL_08_RBAC_POLICIES_functions';
import { MODULE as MOD_08_LOGGING } from './modules/MODUL_08_LOGGING';
import { SUBMODULE as SUBMOD_08_LOGGING_STRUCTURED } from './submodules/PODMODUL_08_LOGGING_STRUCTURED';
import { FUNCTIONS as PODMODUL_08_LOGGING_STRUCTURED_FNS } from './functions/PODMODUL_08_LOGGING_STRUCTURED_functions';
import { SUBMODULE as SUBMOD_08_LOGGING_AUDIT } from './submodules/PODMODUL_08_LOGGING_AUDIT';
import { FUNCTIONS as PODMODUL_08_LOGGING_AUDIT_FNS } from './functions/PODMODUL_08_LOGGING_AUDIT_functions';
import { SUBMODULE as SUBMOD_08_LOGGING_RETENTION } from './submodules/PODMODUL_08_LOGGING_RETENTION';
import { FUNCTIONS as PODMODUL_08_LOGGING_RETENTION_FNS } from './functions/PODMODUL_08_LOGGING_RETENTION_functions';
import { MODULE as MOD_08_TRACING } from './modules/MODUL_08_TRACING';
import { SUBMODULE as SUBMOD_08_TRACING_SPANS } from './submodules/PODMODUL_08_TRACING_SPANS';
import { FUNCTIONS as PODMODUL_08_TRACING_SPANS_FNS } from './functions/PODMODUL_08_TRACING_SPANS_functions';
import { SUBMODULE as SUBMOD_08_TRACING_CONTEXT } from './submodules/PODMODUL_08_TRACING_CONTEXT';
import { FUNCTIONS as PODMODUL_08_TRACING_CONTEXT_FNS } from './functions/PODMODUL_08_TRACING_CONTEXT_functions';
import { SUBMODULE as SUBMOD_08_TRACING_EXPORT } from './submodules/PODMODUL_08_TRACING_EXPORT';
import { FUNCTIONS as PODMODUL_08_TRACING_EXPORT_FNS } from './functions/PODMODUL_08_TRACING_EXPORT_functions';
import { MODULE as MOD_08_TESTING } from './modules/MODUL_08_TESTING';
import { SUBMODULE as SUBMOD_08_TESTING_UNIT } from './submodules/PODMODUL_08_TESTING_UNIT';
import { FUNCTIONS as PODMODUL_08_TESTING_UNIT_FNS } from './functions/PODMODUL_08_TESTING_UNIT_functions';
import { SUBMODULE as SUBMOD_08_TESTING_INTEGRATION } from './submodules/PODMODUL_08_TESTING_INTEGRATION';
import { FUNCTIONS as PODMODUL_08_TESTING_INTEGRATION_FNS } from './functions/PODMODUL_08_TESTING_INTEGRATION_functions';
import { SUBMODULE as SUBMOD_08_TESTING_E2E } from './submodules/PODMODUL_08_TESTING_E2E';
import { FUNCTIONS as PODMODUL_08_TESTING_E2E_FNS } from './functions/PODMODUL_08_TESTING_E2E_functions';
import { MODULE as MOD_08_CICD } from './modules/MODUL_08_CICD';
import { SUBMODULE as SUBMOD_08_CICD_BUILD } from './submodules/PODMODUL_08_CICD_BUILD';
import { FUNCTIONS as PODMODUL_08_CICD_BUILD_FNS } from './functions/PODMODUL_08_CICD_BUILD_functions';
import { SUBMODULE as SUBMOD_08_CICD_DEPLOY } from './submodules/PODMODUL_08_CICD_DEPLOY';
import { FUNCTIONS as PODMODUL_08_CICD_DEPLOY_FNS } from './functions/PODMODUL_08_CICD_DEPLOY_functions';
import { SUBMODULE as SUBMOD_08_CICD_RELEASE } from './submodules/PODMODUL_08_CICD_RELEASE';
import { FUNCTIONS as PODMODUL_08_CICD_RELEASE_FNS } from './functions/PODMODUL_08_CICD_RELEASE_functions';
import { MODULE as MOD_08_ERROR_HANDLING } from './modules/MODUL_08_ERROR_HANDLING';
import { SUBMODULE as SUBMOD_08_ERROR_HANDLING_CAPTURE } from './submodules/PODMODUL_08_ERROR_HANDLING_CAPTURE';
import { FUNCTIONS as PODMODUL_08_ERROR_HANDLING_CAPTURE_FNS } from './functions/PODMODUL_08_ERROR_HANDLING_CAPTURE_functions';
import { SUBMODULE as SUBMOD_08_ERROR_HANDLING_RECOVERY } from './submodules/PODMODUL_08_ERROR_HANDLING_RECOVERY';
import { FUNCTIONS as PODMODUL_08_ERROR_HANDLING_RECOVERY_FNS } from './functions/PODMODUL_08_ERROR_HANDLING_RECOVERY_functions';
import { SUBMODULE as SUBMOD_08_ERROR_HANDLING_REPORTING } from './submodules/PODMODUL_08_ERROR_HANDLING_REPORTING';
import { FUNCTIONS as PODMODUL_08_ERROR_HANDLING_REPORTING_FNS } from './functions/PODMODUL_08_ERROR_HANDLING_REPORTING_functions';
import { MODULE as MOD_08_METRICS } from './modules/MODUL_08_METRICS';
import { SUBMODULE as SUBMOD_08_METRICS_COUNTERS } from './submodules/PODMODUL_08_METRICS_COUNTERS';
import { FUNCTIONS as PODMODUL_08_METRICS_COUNTERS_FNS } from './functions/PODMODUL_08_METRICS_COUNTERS_functions';
import { SUBMODULE as SUBMOD_08_METRICS_GAUGES } from './submodules/PODMODUL_08_METRICS_GAUGES';
import { FUNCTIONS as PODMODUL_08_METRICS_GAUGES_FNS } from './functions/PODMODUL_08_METRICS_GAUGES_functions';
import { SUBMODULE as SUBMOD_08_METRICS_HISTOGRAMS } from './submodules/PODMODUL_08_METRICS_HISTOGRAMS';
import { FUNCTIONS as PODMODUL_08_METRICS_HISTOGRAMS_FNS } from './functions/PODMODUL_08_METRICS_HISTOGRAMS_functions';

import { ARTIFACTS } from './artifacts';
import { TOOLCHAINS } from './toolchains';
import { BUILD_STEPS } from './build_steps';
import { VERIFICATION_ACTIVITIES } from './verification';
import { EVIDENCE_ITEMS } from './evidence';
import { STANDARD_OBLIGATIONS } from './standards';
import { INTEGRATION_PATTERNS } from './integrations';
import { ENVIRONMENTS } from './environments';
import { RELATIONS } from './relations';
import { DEFINITIONS } from './definitions';
import { CONTEXT_FRAMES } from './context_frames';

export const DOMENA_PACK: DomainPack = {
    domain: DOMAIN,
    categories: [CAT_08_CRYPTO, CAT_08_AUTH],
    subcategories: [SUBCAT_08_SYMMETRIC, SUBCAT_08_ASYMMETRIC, SUBCAT_08_MFA],
    modules: [MOD_08_AES,
        MOD_08_RSA,
        MOD_08_TOTP,
        MOD_08_HASHING,
        MOD_08_KEY_DERIVATION,
        MOD_08_SECURE_RANDOM,
        MOD_08_VULNERABILITY, MOD_08_AUTH, MOD_08_RBAC, MOD_08_LOGGING, MOD_08_TRACING, MOD_08_TESTING, MOD_08_CICD, MOD_08_ERROR_HANDLING, MOD_08_METRICS],
    submodules: [SUBMOD_08_AES_CORE,
        SUBMOD_08_RSA_CORE,
        SUBMOD_08_TOTP_CORE,
        SUBMOD_08_HASHING_CORE,
        SUBMOD_08_KEY_DERIVATION_CORE,
        SUBMOD_08_SECURE_RANDOM_CORE,
        SUBMOD_08_VULNERABILITY_CORE, SUBMOD_08_AUTH_JWT, SUBMOD_08_AUTH_OAUTH, SUBMOD_08_AUTH_SESSION, SUBMOD_08_RBAC_ROLES, SUBMOD_08_RBAC_PERMISSIONS, SUBMOD_08_RBAC_POLICIES, SUBMOD_08_LOGGING_STRUCTURED, SUBMOD_08_LOGGING_AUDIT, SUBMOD_08_LOGGING_RETENTION, SUBMOD_08_TRACING_SPANS, SUBMOD_08_TRACING_CONTEXT, SUBMOD_08_TRACING_EXPORT, SUBMOD_08_TESTING_UNIT, SUBMOD_08_TESTING_INTEGRATION, SUBMOD_08_TESTING_E2E, SUBMOD_08_CICD_BUILD, SUBMOD_08_CICD_DEPLOY, SUBMOD_08_CICD_RELEASE, SUBMOD_08_ERROR_HANDLING_CAPTURE, SUBMOD_08_ERROR_HANDLING_RECOVERY, SUBMOD_08_ERROR_HANDLING_REPORTING, SUBMOD_08_METRICS_COUNTERS, SUBMOD_08_METRICS_GAUGES, SUBMOD_08_METRICS_HISTOGRAMS],
    functions: [...SUBMOD_08_AES_CORE_FNS,
        ...SUBMOD_08_RSA_CORE_FNS,
        ...SUBMOD_08_TOTP_CORE_FNS,
        ...SUBMOD_08_HASHING_CORE_FNS,
        ...SUBMOD_08_KEY_DERIVATION_CORE_FNS,
        ...SUBMOD_08_SECURE_RANDOM_CORE_FNS,
        ...SUBMOD_08_VULNERABILITY_CORE_FNS, ...PODMODUL_08_AUTH_JWT_FNS, ...PODMODUL_08_AUTH_OAUTH_FNS, ...PODMODUL_08_AUTH_SESSION_FNS, ...PODMODUL_08_RBAC_ROLES_FNS, ...PODMODUL_08_RBAC_PERMISSIONS_FNS, ...PODMODUL_08_RBAC_POLICIES_FNS, ...PODMODUL_08_LOGGING_STRUCTURED_FNS, ...PODMODUL_08_LOGGING_AUDIT_FNS, ...PODMODUL_08_LOGGING_RETENTION_FNS, ...PODMODUL_08_TRACING_SPANS_FNS, ...PODMODUL_08_TRACING_CONTEXT_FNS, ...PODMODUL_08_TRACING_EXPORT_FNS, ...PODMODUL_08_TESTING_UNIT_FNS, ...PODMODUL_08_TESTING_INTEGRATION_FNS, ...PODMODUL_08_TESTING_E2E_FNS, ...PODMODUL_08_CICD_BUILD_FNS, ...PODMODUL_08_CICD_DEPLOY_FNS, ...PODMODUL_08_CICD_RELEASE_FNS, ...PODMODUL_08_ERROR_HANDLING_CAPTURE_FNS, ...PODMODUL_08_ERROR_HANDLING_RECOVERY_FNS, ...PODMODUL_08_ERROR_HANDLING_REPORTING_FNS, ...PODMODUL_08_METRICS_COUNTERS_FNS, ...PODMODUL_08_METRICS_GAUGES_FNS, ...PODMODUL_08_METRICS_HISTOGRAMS_FNS],
    relations: [...RELATIONS],
    definitions: [...DEFINITIONS],
    contextFrames: [...CONTEXT_FRAMES],
    artifacts: ARTIFACTS,
    toolchains: TOOLCHAINS,
    buildSteps: BUILD_STEPS,
    environments: [...ENVIRONMENTS],
    verificationActivities: VERIFICATION_ACTIVITIES,
    evidenceItems: EVIDENCE_ITEMS,
    standardObligations: STANDARD_OBLIGATIONS,
    integrationPatterns: INTEGRATION_PATTERNS
};
