import { IntegrationPattern } from '../../registry/types';

export const INTEGRATION_PATTERNS: readonly IntegrationPattern[] = [
    {
        id: 'INTEGRACIJA_08_SIEM',
        displayNameSL: 'SIEM Integration',
        descriptionSL: 'Integracija s SIEM sistemom',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['siem', 'logging', 'security'],
        integrationKind: 'EVENT_STREAM',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_13',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'SYSLOG',
        dataFormat: 'CEF',
        synchronous: false,
        securityRequirements: ['ENCRYPTION', 'INTEGRITY']
    },
    {
        id: 'INTEGRACIJA_08_VAULT',
        displayNameSL: 'Secrets Management',
        descriptionSL: 'Upravljanje skrivnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['PODMODUL_08_AES_CORE', 'secrets', 'hashicorp'],
        integrationKind: 'API',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_11',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'HTTPS',
        dataFormat: 'JSON',
        synchronous: true,
        securityRequirements: ['ENCRYPTION', 'AUDIT_LOG']
    },
    {
        id: 'INTEGRACIJA_08_IDP',
        displayNameSL: 'Identity Provider',
        descriptionSL: 'Ponudnik identitete',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['idp', 'oauth', 'oidc'],
        integrationKind: 'API',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_02',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'OIDC',
        dataFormat: 'JWT',
        synchronous: true,
        securityRequirements: ['TLS_1_3', 'TOKEN_VALIDATION']
    },
    {
        id: 'INTEGRACIJA_08_WAF',
        displayNameSL: 'Web Application Firewall',
        descriptionSL: 'Pozarni zid za spletne aplikacije',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['waf', 'firewall', 'protection'],
        integrationKind: 'API',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_01',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'HTTP',
        dataFormat: 'HTTP_MESSAGE',
        synchronous: true,
        securityRequirements: ['RULE_ENFORCEMENT', 'LOGGING']
    },
    {
        id: 'INTEGRACIJA_08_VULNERABILITY_DB',
        displayNameSL: 'Vulnerability Database',
        descriptionSL: 'Baza ranljivosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['nvd', 'cve', 'vulnerability'],
        integrationKind: 'API',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_03',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'HTTPS',
        dataFormat: 'JSON',
        synchronous: true,
        securityRequirements: ['RATE_LIMITING']
    },
    {
        id: 'INTEGRACIJA_08_TICKETING',
        displayNameSL: 'Security Ticketing',
        descriptionSL: 'Varnostno upravljanje zahtevkov',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/integrations',
        domainId: 'DOMENA_08',
        type: 'INTEGRATION_PATTERN',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['ticketing', 'jira', 'PODMODUL_08_AES_CORE'],
        integrationKind: 'API',
        sourceDomainId: 'DOMENA_08',
        targetDomainId: 'DOMENA_16',
        sourceModuleIds: [],
        targetModuleIds: [],
        protocol: 'HTTPS',
        dataFormat: 'JSON',
        synchronous: true,
        securityRequirements: ['AUDIT_LOG']
    }
];
