import { VerificationActivity } from '../../registry/types';

export const VERIFICATION_ACTIVITIES: readonly VerificationActivity[] = [
    {
        id: 'VERIFIKACIJA_08_SAST_REVIEW',
        displayNameSL: 'SAST Review',
        descriptionSL: 'Pregled SAST rezultatov',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sast', 'review'],
        verificationKind: 'STATIC_ANALYSIS',
        targetArtifactIds: ['ARTEFAKT_08_SAST_REPORT'],
        targetStepIds: ['KORAK_08_SAST'],
        toolchainId: 'ORODJE_08_SEMGREP',
        passThreshold: 100,
        blocking: true,
        reportFormat: 'sarif'
    },
    {
        id: 'VERIFIKACIJA_08_VULN_ASSESSMENT',
        displayNameSL: 'Vulnerability Assessment',
        descriptionSL: 'Ocena ranljivosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['vulnerability', 'assessment'],
        verificationKind: 'SECURITY_SCAN',
        targetArtifactIds: ['ARTEFAKT_08_VULNERABILITY_REPORT'],
        targetStepIds: ['KORAK_08_VULN_SCAN'],
        toolchainId: 'ORODJE_08_TRIVY',
        passThreshold: 100,
        blocking: true,
        reportFormat: 'json'
    },
    {
        id: 'VERIFIKACIJA_08_SECRETS_AUDIT',
        displayNameSL: 'Secrets Audit',
        descriptionSL: 'Revizija skrivnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['secrets', 'audit'],
        verificationKind: 'SECURITY_SCAN',
        targetArtifactIds: ['ARTEFAKT_08_SECRETS_SCAN'],
        targetStepIds: ['KORAK_08_SECRETS_SCAN'],
        toolchainId: 'ORODJE_08_GITLEAKS',
        passThreshold: 100,
        blocking: true,
        reportFormat: 'json'
    },
    {
        id: 'VERIFIKACIJA_08_DAST_REVIEW',
        displayNameSL: 'DAST Review',
        descriptionSL: 'Pregled DAST rezultatov',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['dast', 'review'],
        verificationKind: 'SECURITY_SCAN',
        targetArtifactIds: ['ARTEFAKT_08_DAST_REPORT'],
        targetStepIds: ['KORAK_08_DAST'],
        toolchainId: 'ORODJE_08_ZAP',
        passThreshold: 80,
        blocking: true,
        reportFormat: 'json'
    },
    {
        id: 'VERIFIKACIJA_08_COMPLIANCE_AUDIT',
        displayNameSL: 'Compliance Audit',
        descriptionSL: 'Revizija skladnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['compliance', 'audit'],
        verificationKind: 'COMPLIANCE_CHECK',
        targetArtifactIds: ['ARTEFAKT_08_COMPLIANCE_REPORT'],
        targetStepIds: ['KORAK_08_COMPLIANCE_CHECK'],
        toolchainId: null,
        passThreshold: 100,
        blocking: true,
        reportFormat: 'json'
    },
    {
        id: 'VERIFIKACIJA_08_PENTEST_REVIEW',
        displayNameSL: 'Pentest Review',
        descriptionSL: 'Pregled penetracijskega testa',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/verification',
        domainId: 'DOMENA_08',
        type: 'VERIFICATION_ACTIVITY',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['pentest', 'review'],
        verificationKind: 'SECURITY_SCAN',
        targetArtifactIds: ['ARTEFAKT_08_PENTEST_REPORT'],
        targetStepIds: ['KORAK_08_PENTEST'],
        toolchainId: 'ORODJE_08_NUCLEI',
        passThreshold: 80,
        blocking: false,
        reportFormat: 'json'
    }
];
