import { BuildStep } from '../../registry/types';

export const BUILD_STEPS: readonly BuildStep[] = [
    {
        id: 'KORAK_08_POLICY_DESIGN',
        displayNameSL: 'Security Policy Design',
        descriptionSL: 'Nacrtovanje varnostne politike',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['policy', 'design'],
        phase: 'DEPENDENCY_RESOLUTION',
        toolchainId: 'ORODJE_08_COSIGN',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_SECURITY_POLICY'],
        dependsOnStepIds: [],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 300000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: true
    },
    {
        id: 'KORAK_08_SBOM_GEN',
        displayNameSL: 'SBOM Generation',
        descriptionSL: 'Generiranje SBOM',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sbom', 'syft'],
        phase: 'COMPILE',
        toolchainId: 'ORODJE_08_SYFT',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_SBOM'],
        dependsOnStepIds: [],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 600000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: true
    },
    {
        id: 'KORAK_08_SAST',
        displayNameSL: 'Static Analysis',
        descriptionSL: 'Staticna analiza varnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['sast', 'semgrep'],
        phase: 'VERIFY',
        toolchainId: 'ORODJE_08_SEMGREP',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_SAST_REPORT'],
        dependsOnStepIds: [],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 900000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: true
    },
    {
        id: 'KORAK_08_SECRETS_SCAN',
        displayNameSL: 'Secrets Scanning',
        descriptionSL: 'Skeniranje skrivnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['secrets', 'gitleaks'],
        phase: 'VERIFY',
        toolchainId: 'ORODJE_08_GITLEAKS',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_SECRETS_SCAN'],
        dependsOnStepIds: [],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 300000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: true
    },
    {
        id: 'KORAK_08_VULN_SCAN',
        displayNameSL: 'Vulnerability Scanning',
        descriptionSL: 'Skeniranje ranljivosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['vulnerability', 'trivy', 'grype'],
        phase: 'VERIFY',
        toolchainId: 'ORODJE_08_TRIVY',
        inputArtifactIds: ['ARTEFAKT_08_SBOM'],
        outputArtifactIds: ['ARTEFAKT_08_VULNERABILITY_REPORT'],
        dependsOnStepIds: ['KORAK_08_SBOM_GEN'],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 600000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: false
    },
    {
        id: 'KORAK_08_DAST',
        displayNameSL: 'Dynamic Analysis',
        descriptionSL: 'Dinamicna analiza varnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['dast', 'zap'],
        phase: 'TEST',
        toolchainId: 'ORODJE_08_ZAP',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_DAST_REPORT'],
        dependsOnStepIds: ['KORAK_08_SAST'],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 1800000,
        retryPolicy: { maxRetries: 2, backoffMs: 30000 },
        cacheable: false
    },
    {
        id: 'KORAK_08_PENTEST',
        displayNameSL: 'Penetration Testing',
        descriptionSL: 'Penetracijski test',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['pentest', 'nuclei'],
        phase: 'TEST',
        toolchainId: 'ORODJE_08_NUCLEI',
        inputArtifactIds: [],
        outputArtifactIds: ['ARTEFAKT_08_PENTEST_REPORT'],
        dependsOnStepIds: ['KORAK_08_DAST'],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 3600000,
        retryPolicy: { maxRetries: 1, backoffMs: 60000 },
        cacheable: false
    },
    {
        id: 'KORAK_08_COMPLIANCE_CHECK',
        displayNameSL: 'Compliance Check',
        descriptionSL: 'Preverjanje skladnosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['compliance', 'audit'],
        phase: 'VERIFY',
        toolchainId: 'ORODJE_08_TRIVY',
        inputArtifactIds: ['ARTEFAKT_08_SAST_REPORT', 'ARTEFAKT_08_VULNERABILITY_REPORT'],
        outputArtifactIds: ['ARTEFAKT_08_COMPLIANCE_REPORT'],
        dependsOnStepIds: ['KORAK_08_SAST', 'KORAK_08_VULN_SCAN'],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 300000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: true
    },
    {
        id: 'KORAK_08_REMEDIATION',
        displayNameSL: 'Vulnerability Remediation',
        descriptionSL: 'Odprava ranljivosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/build_steps',
        domainId: 'DOMENA_08',
        type: 'BUILD_STEP',
        version: '1.0.0',
        hash: '',
        links: [],
        tags: ['remediation', 'fix'],
        phase: 'DEPLOY',
        toolchainId: 'ORODJE_08_TRIVY',
        inputArtifactIds: ['ARTEFAKT_08_VULNERABILITY_REPORT'],
        outputArtifactIds: [],
        dependsOnStepIds: ['KORAK_08_VULN_SCAN'],
        environmentId: 'OKOLJE_08_SECURITY_BUILD',
        timeout: 600000,
        retryPolicy: { maxRetries: 2, backoffMs: 5000 },
        cacheable: false
    }
];
