import { StandardObligation } from '../../registry/types';

export const STANDARD_OBLIGATIONS: readonly StandardObligation[] = [
    {
        id: 'STANDARD_08_OWASP_TOP10',
        displayNameSL: 'OWASP Top 10',
        descriptionSL: 'OWASP Top 10 varnostnih ranljivosti',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/standards',
        domainId: 'DOMENA_08',
        type: 'STANDARD_OBLIGATION',
        version: '1.0.0',
        hash: '',
        links: ['https://owasp.org/www-project-top-ten/'],
        tags: ['owasp', 'top10', 'web'],
        standardCategory: 'SECURITY',
        standardId: 'OWASP-TOP10-2021',
        standardName: 'OWASP Top 10 2021',
        clause: 'A01-A10',
        requiredEvidenceIds: ['EVI_08_SAST_REPORT'],
        requiredVerificationIds: ['VERIFIKACIJA_08_SAST_REVIEW', 'VERIFIKACIJA_08_DAST_REVIEW'],
        constrainedStepIds: ['KORAK_08_SAST', 'KORAK_08_DAST'],
        constrainedArtifactIds: ['ARTEFAKT_08_SAST_REPORT', 'ARTEFAKT_08_DAST_REPORT'],
        failOnMissing: true
    },
    {
        id: 'STANDARD_08_ISO27001',
        displayNameSL: 'ISO 27001',
        descriptionSL: 'ISO 27001 informacijska varnost',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/standards',
        domainId: 'DOMENA_08',
        type: 'STANDARD_OBLIGATION',
        version: '1.0.0',
        hash: '',
        links: ['https://www.iso.org/isoiec-27001-information-security.html'],
        tags: ['iso27001', 'isms', 'security'],
        standardCategory: 'SECURITY',
        standardId: 'ISO-27001-2022',
        standardName: 'ISO/IEC 27001:2022',
        clause: 'Annex A controls',
        requiredEvidenceIds: ['EVI_08_COMPLIANCE_REPORT'],
        requiredVerificationIds: ['VERIFIKACIJA_08_COMPLIANCE_AUDIT'],
        constrainedStepIds: ['KORAK_08_COMPLIANCE_CHECK'],
        constrainedArtifactIds: ['ARTEFAKT_08_COMPLIANCE_REPORT'],
        failOnMissing: false
    },
    {
        id: 'STANDARD_08_SOC2',
        displayNameSL: 'SOC 2',
        descriptionSL: 'SOC 2 Type II',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/standards',
        domainId: 'DOMENA_08',
        type: 'STANDARD_OBLIGATION',
        version: '1.0.0',
        hash: '',
        links: ['https://www.aicpa.org/soc2'],
        tags: ['soc2', 'audit', 'trust'],
        standardCategory: 'INDUSTRY',
        standardId: 'SOC2-TYPE2',
        standardName: 'SOC 2 Type II',
        clause: 'Trust Services Criteria',
        requiredEvidenceIds: ['EVI_08_COMPLIANCE_REPORT'],
        requiredVerificationIds: ['VERIFIKACIJA_08_COMPLIANCE_AUDIT'],
        constrainedStepIds: ['KORAK_08_COMPLIANCE_CHECK'],
        constrainedArtifactIds: ['ARTEFAKT_08_COMPLIANCE_REPORT'],
        failOnMissing: false
    },
    {
        id: 'STANDARD_08_NIST_800_53',
        displayNameSL: 'NIST 800-53',
        descriptionSL: 'NIST SP 800-53 varnostni kontroli',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/standards',
        domainId: 'DOMENA_08',
        type: 'STANDARD_OBLIGATION',
        version: '1.0.0',
        hash: '',
        links: ['https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final'],
        tags: ['nist', '800-53', 'controls'],
        standardCategory: 'SECURITY',
        standardId: 'NIST-SP-800-53-R5',
        standardName: 'NIST SP 800-53 Rev. 5',
        clause: 'All control families',
        requiredEvidenceIds: [],
        requiredVerificationIds: [],
        constrainedStepIds: [],
        constrainedArtifactIds: [],
        failOnMissing: false
    },
    {
        id: 'STANDARD_08_CWE_SANS_25',
        displayNameSL: 'CWE/SANS Top 25',
        descriptionSL: 'CWE/SANS Top 25 nevarnih napak',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/standards',
        domainId: 'DOMENA_08',
        type: 'STANDARD_OBLIGATION',
        version: '1.0.0',
        hash: '',
        links: ['https://cwe.mitre.org/top25/'],
        tags: ['cwe', 'sans', 'top25'],
        standardCategory: 'SECURITY',
        standardId: 'CWE-SANS-TOP25-2023',
        standardName: 'CWE/SANS Top 25 2023',
        clause: 'CWE-787 to CWE-918',
        requiredEvidenceIds: ['EVI_08_SAST_REPORT'],
        requiredVerificationIds: ['VERIFIKACIJA_08_SAST_REVIEW'],
        constrainedStepIds: ['KORAK_08_SAST'],
        constrainedArtifactIds: ['ARTEFAKT_08_SAST_REPORT'],
        failOnMissing: true
    }
];
