import { Toolchain } from '../../registry/types';

export const TOOLCHAINS: readonly Toolchain[] = [
    {
        id: 'ORODJE_08_SEMGREP',
        displayNameSL: 'Semgrep',
        descriptionSL: 'Semgrep SAST orodje',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://semgrep.dev'],
        tags: ['semgrep', 'sast', 'static'],
        toolchainCategory: 'SECURITY',
        vendor: 'Semgrep Inc',
        versionConstraint: '>=1.50.0',
        command: ['semgrep'],
        inputFormats: ['*'],
        outputFormats: ['sarif', 'json'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_TRIVY',
        displayNameSL: 'Trivy',
        descriptionSL: 'Trivy vulnerability scanner',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://trivy.dev'],
        tags: ['trivy', 'vulnerability', 'scanner'],
        toolchainCategory: 'SECURITY',
        vendor: 'Aqua Security',
        versionConstraint: '>=0.48.0',
        command: ['trivy'],
        inputFormats: ['*'],
        outputFormats: ['json', 'sarif', 'table'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_GRYPE',
        displayNameSL: 'Grype',
        descriptionSL: 'Grype vulnerability scanner',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://github.com/anchore/grype'],
        tags: ['grype', 'vulnerability', 'anchore'],
        toolchainCategory: 'SECURITY',
        vendor: 'Anchore',
        versionConstraint: '>=0.74.0',
        command: ['grype'],
        inputFormats: ['sbom', 'image'],
        outputFormats: ['json', 'sarif', 'table'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_SYFT',
        displayNameSL: 'Syft',
        descriptionSL: 'Syft SBOM generator',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://github.com/anchore/syft'],
        tags: ['syft', 'sbom', 'anchore'],
        toolchainCategory: 'SECURITY',
        vendor: 'Anchore',
        versionConstraint: '>=1.0.0',
        command: ['syft'],
        inputFormats: ['*'],
        outputFormats: ['spdx-json', 'cyclonedx-json'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_GITLEAKS',
        displayNameSL: 'Gitleaks',
        descriptionSL: 'Gitleaks secrets scanner',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://gitleaks.io'],
        tags: ['gitleaks', 'secrets', 'scanner'],
        toolchainCategory: 'SECURITY',
        vendor: 'Gitleaks',
        versionConstraint: '>=8.18.0',
        command: ['gitleaks'],
        inputFormats: ['*'],
        outputFormats: ['json', 'sarif'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_ZAP',
        displayNameSL: 'OWASP ZAP',
        descriptionSL: 'OWASP ZAP DAST orodje',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://www.zaproxy.org'],
        tags: ['zap', 'dast', 'owasp'],
        toolchainCategory: 'SECURITY',
        vendor: 'OWASP',
        versionConstraint: '>=2.14.0',
        command: ['zap-cli'],
        inputFormats: ['url'],
        outputFormats: ['json', 'html', 'xml'],
        environmentVariables: {},
        deterministic: false,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_NUCLEI',
        displayNameSL: 'Nuclei',
        descriptionSL: 'Nuclei vulnerability scanner',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://nuclei.projectdiscovery.io'],
        tags: ['nuclei', 'scanner', 'templates'],
        toolchainCategory: 'SECURITY',
        vendor: 'ProjectDiscovery',
        versionConstraint: '>=3.1.0',
        command: ['nuclei'],
        inputFormats: ['url', 'ip'],
        outputFormats: ['json', 'sarif'],
        environmentVariables: {},
        deterministic: false,
        platforms: ['linux', 'macos', 'windows']
    },
    {
        id: 'ORODJE_08_COSIGN',
        displayNameSL: 'Cosign',
        descriptionSL: 'Cosign container signing',
        path: 'knowbank/domene/DOMENA_08_VARNOSTNI_SISTEMI/toolchains',
        domainId: 'DOMENA_08',
        type: 'TOOLCHAIN',
        version: '1.0.0',
        hash: '',
        links: ['https://github.com/sigstore/cosign'],
        tags: ['cosign', 'signing', 'sigstore'],
        toolchainCategory: 'SECURITY',
        vendor: 'Sigstore',
        versionConstraint: '>=2.2.0',
        command: ['cosign'],
        inputFormats: ['image'],
        outputFormats: ['signature'],
        environmentVariables: {},
        deterministic: true,
        platforms: ['linux', 'macos', 'windows']
    }
];
